language: node_js
node_js:
  - "6"

before_script:
  - npm install -g npm@latest
  - npm install -g gulpjs/gulp-cli bower pug stylus
  - npm install

script:
  - gulp test

env:
  - PORT=7777
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8