language: node_js
node_js:
  - "6.6.0"
#  - "6"

before_script:
  - npm install -g npm@latest
  - npm install -g gulpjs/gulp-cli pug
  - npm install

script:
  - gulp test

env:
  - PORT=7777
  - MONGODB_URI=mongodb://rb7373:rb7373@ds035786.mlab.com:35786/heroku_xdrvz1pv
#  - CXX=g++-4.8

#addons:
#  apt:
#    sources:
#      - ubuntu-toolchain-r-test
#    packages:
#      - g++-4.8